/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.117
 * Generated at: 2026-04-26 06:58:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.model.Student;

public final class studentupdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.model.Student");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>Update Student - Hostel Management</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\">\n");
      out.write("    <style>\n");
      out.write("        body { background: #f0f2f5; }\n");
      out.write("        .form-card { border: none; border-radius: 15px; box-shadow: 0 5px 20px rgba(0,0,0,0.1); }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"container py-5\">\n");
      out.write("    <div class=\"row justify-content-center\">\n");
      out.write("        <div class=\"col-md-8\">\n");
      out.write("            <div class=\"card form-card p-4\">\n");
      out.write("                <h3 class=\"text-center mb-4\">✏️ Update Student</h3>\n");
      out.write("\n");
      out.write("                ");
 String message = (String) request.getAttribute("message"); 
      out.write("\n");
      out.write("                ");
 String messageType = (String) request.getAttribute("messageType"); 
      out.write("\n");
      out.write("                ");
 if (message != null) { 
      out.write("\n");
      out.write("                    <div class=\"alert alert-");
      out.print( "success".equals(messageType) ? "success" : "danger" );
      out.write(" alert-dismissible fade show\">\n");
      out.write("                        ");
      out.print( message );
      out.write("\n");
      out.write("                        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\"></button>\n");
      out.write("                    </div>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("                ");
 Student student = (Student) request.getAttribute("student"); 
      out.write("\n");
      out.write("\n");
      out.write("                ");
 if (student == null) { 
      out.write("\n");
      out.write("                <!-- Search form to find student by ID -->\n");
      out.write("                <form action=\"UpdateStudentServlet\" method=\"get\" class=\"text-center\">\n");
      out.write("                    <div class=\"row justify-content-center g-3\">\n");
      out.write("                        <div class=\"col-md-6\">\n");
      out.write("                            <label class=\"form-label\">Enter Student ID</label>\n");
      out.write("                            <input type=\"number\" name=\"id\" class=\"form-control\" required>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-12 mt-3\">\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-primary btn-lg px-5\">Find Student</button>\n");
      out.write("                            <a href=\"index.jsp\" class=\"btn btn-outline-secondary btn-lg px-5 ms-2\">Back</a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </form>\n");
      out.write("                ");
 } else { 
      out.write("\n");
      out.write("                <!-- Update form with student data -->\n");
      out.write("                <form action=\"UpdateStudentServlet\" method=\"post\">\n");
      out.write("                    <input type=\"hidden\" name=\"id\" value=\"");
      out.print( student.getId() );
      out.write("\">\n");
      out.write("                    <div class=\"row g-3\">\n");
      out.write("                        <div class=\"col-md-6\">\n");
      out.write("                            <label class=\"form-label\">Student ID</label>\n");
      out.write("                            <input type=\"text\" class=\"form-control\" value=\"");
      out.print( student.getId() );
      out.write("\" disabled>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-6\">\n");
      out.write("                            <label class=\"form-label\">Full Name *</label>\n");
      out.write("                            <input type=\"text\" name=\"name\" class=\"form-control\" value=\"");
      out.print( student.getName() != null ? student.getName() : "" );
      out.write("\" required>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-6\">\n");
      out.write("                            <label class=\"form-label\">Email *</label>\n");
      out.write("                            <input type=\"email\" name=\"email\" class=\"form-control\" value=\"");
      out.print( student.getEmail() != null ? student.getEmail() : "" );
      out.write("\" required>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-6\">\n");
      out.write("                            <label class=\"form-label\">Phone *</label>\n");
      out.write("                            <input type=\"text\" name=\"phone\" class=\"form-control\" value=\"");
      out.print( student.getPhone() != null ? student.getPhone() : "" );
      out.write("\" required>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-6\">\n");
      out.write("                            <label class=\"form-label\">Room Number</label>\n");
      out.write("                            <input type=\"text\" name=\"roomNumber\" class=\"form-control\" value=\"");
      out.print( student.getRoomNumber() != null ? student.getRoomNumber() : "" );
      out.write("\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-6\">\n");
      out.write("                            <label class=\"form-label\">Course</label>\n");
      out.write("                            <input type=\"text\" name=\"course\" class=\"form-control\" value=\"");
      out.print( student.getCourse() != null ? student.getCourse() : "" );
      out.write("\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-6\">\n");
      out.write("                            <label class=\"form-label\">Year</label>\n");
      out.write("                            <select name=\"year\" class=\"form-select\">\n");
      out.write("                                <option value=\"\">Select Year</option>\n");
      out.write("                                <option value=\"1st\" ");
      out.print( "1st".equals(student.getYear()) ? "selected" : "" );
      out.write(">1st Year</option>\n");
      out.write("                                <option value=\"2nd\" ");
      out.print( "2nd".equals(student.getYear()) ? "selected" : "" );
      out.write(">2nd Year</option>\n");
      out.write("                                <option value=\"3rd\" ");
      out.print( "3rd".equals(student.getYear()) ? "selected" : "" );
      out.write(">3rd Year</option>\n");
      out.write("                                <option value=\"4th\" ");
      out.print( "4th".equals(student.getYear()) ? "selected" : "" );
      out.write(">4th Year</option>\n");
      out.write("                            </select>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-12\">\n");
      out.write("                            <label class=\"form-label\">Address</label>\n");
      out.write("                            <textarea name=\"address\" class=\"form-control\" rows=\"3\">");
      out.print( student.getAddress() != null ? student.getAddress() : "" );
      out.write("</textarea>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-12 text-center mt-4\">\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-warning btn-lg px-5\">Update Student</button>\n");
      out.write("                            <a href=\"index.jsp\" class=\"btn btn-outline-secondary btn-lg px-5 ms-2\">Back</a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </form>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
